### PR TITLE
Merge lendup upstream

### PR DESCRIPTION
**Pull request by jgogstad**
```
> git log --first-parent master..head
6c4f436 Minor adjustments after upstream merge
8585280 Travis build mounts coursier cache
dea8dd0 Upgrade fs2, don't cross publish scala 2.11
2b18a7f Merge remote-tracking branch 'lendup/master' into merge-lendup
```

### CODE REVIEW

**Comment by rolandomanrique** [comment]
@jgogstad @gafiatulin also feel free to change `com.lendup.fs2-blobstore` group id so we can start publishing this to sonatype without LendUp's gpg keys. I wanted to do this when I created this new repo but got stuck because when we did this at LendUp I was getting help from @stew on this whole set up and haven't had time to re-learn all the magic incantations to make sonatype releases work.

**Comment by jgogstad** [comment]
Yeah, just filed a ticket for a new group, https://issues.sonatype.org/browse/OSSRH-55141

I'll sort the keys out tomorrow

**Comment by jgogstad** [comment]
@rolandomanrique: Sonatype asks for proof of github organization ownership, can you add @gafiatulin and myself to the organization please?

**Comment by rolandomanrique** [comment]
@jgogstad done. Added you both as org owners.

**Pull request merged**
