### PR TITLE
FS2 3.0 & CE3 

### PR DESCRIPTION
**Pull request by gafiatulin**
Update code to the released versions of [FS2](https://github.com/typelevel/fs2/releases/tag/v3.0.0) and [Cats Effect](https://github.com/typelevel/cats-effect/releases/tag/v3.0.0).

### CODE REVIEW

**Review by jgogstad — APPROVED** [review]
🎉

**Comment by worace** [comment]
Awesome to see this! I was wondering if there has been a release of this version yet. The latest I see in [maven is 0.8.0-beta3](https://search.maven.org/artifact/com.github.fs2-blobstore/core_2.13/0.8.0-beta3/jar) which looks like it still has fs2 2.5.4.

Based on the dates though it looks like that version was pushed after this PR. Maybe I am missing something?

**Comment by gafiatulin** [comment]
@worace Yes, you are right, 0.8.0-beta3 is based on CE2/fs2 2.5.4. 

I published `0.9.0-beta3` based on CE3, it should land to maven central soon.

As we wait for the rest of the ecosystem to move to CE3 there might be couple more versions targeting CE2, they should go to `0.8.XX(-YY)`. Versions based on CE3 would go to `0.9.XX(-YY)` and higher.

cc @jgogstad

**Comment by worace** [comment]
Awesome, I will watch out for it. I just have this and a couple more libraries on my CE3 upgrade path. Thanks for working on these upgrades.

**Pull request merged**
